[versions]
kotlin = "1.8.22"

pv = "2.1.5"

lavaplayer = "2.2.4"
lavaplayer-youtube-source = "ff19b6f1751262ecba7b81fcf391b961008962d1-SNAPSHOT"

pv-gradle-plugin = "1.0.2-SNAPSHOT"
shadow = "8.1.1"

[libraries]
pv-server = { module = "su.plo.voice.api:server", version.ref = "pv" }
pv-proxy = { module = "su.plo.voice.api:proxy", version.ref = "pv" }

lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:common", version.ref = "lavaplayer-youtube-source" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pv-entrypoints = { id = "su.plo.voice.plugin.entrypoints", version.ref = "pv-gradle-plugin" }
pv-java-templates = { id = "su.plo.voice.plugin.java-templates", version.ref = "pv-gradle-plugin" }
