[versions]
kotlin = "1.8.22"

pv = "2.1.5"

lavaplayer = "d2e2949f67612c0b5ccb23205d83d0d386cf552e-SNAPSHOT"
lavaplayer-youtube-source = "1.18.1"
lavasrc = "4.8.1"

pv-gradle-plugin = "1.0.2-SNAPSHOT"
shadow = "8.1.1"

[libraries]
pv-server = { module = "su.plo.voice.api:server", version.ref = "pv" }
pv-proxy = { module = "su.plo.voice.api:proxy", version.ref = "pv" }

lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:common", version.ref = "lavaplayer-youtube-source" }
lavasrc = { module = "com.github.topi314.lavasrc:lavasrc", version.ref = "lavasrc" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pv-entrypoints = { id = "su.plo.voice.plugin.entrypoints", version.ref = "pv-gradle-plugin" }
pv-java-templates = { id = "su.plo.voice.plugin.java-templates", version.ref = "pv-gradle-plugin" }
