name: Publish Release

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          16
          17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Modrinth/CurseForge
      uses: Apehum/mc-publish@v1.1
      with:        
        modrinth-id: Kx9d4acU
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        changelog-file: changelog.md
        files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
        files-secondary: build/libs/*-@(disabled).jar
        
        loaders: |
          fabric
          forge
          neoforge
          paper
          spigot
          velocity
          bungeecord
        game-versions: |
          1.16.5
          1.17.1
          1.18.2
          1.19.2
          1.19.3
          1.19.4
          1.20
          1.20.1
          1.20.2
          1.20.3
          1.20.4
          1.20.5
          1.20.6
          1.21
          1.21.1
        
    - name: Publish to GitHub
      uses: Apehum/mc-publish@v1.1
      with:
        files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
        files-secondary: build/libs/*-@(disabled).jar
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: false
        changelog-file: changelog.md
